language: java
jdk:
    - openjdk8

branches:
    only:
        - master

# Travis CI server HOME
cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일 알림
notifications:
    email:
        recipients:
            - setong17@gmail.com
